# -*- coding: utf-8 -*-
"""Modelo Macrozonas 2.0

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ocavegqieKwXCPAibg_wd3tP1MueHhXD
"""

# =======================
# MILP "completo" para test: servicio + reequilibrio + inventario por franja
# =======================
import pandas as pd, numpy as np
from pathlib import Path
import gurobipy as gp
from gurobipy import GRB
import math

# -------- Rutas y columnas
OUT = Path("/content/outputs")
A_PATH     = OUT/"A_final_SLA_soft_BUCKETS_covgoal.csv"   # arcos servicio (i,j,h) permitidos
TIME_PATH  = OUT/"times_macro_macro_bucket.csv"           # tiempos (p50/p90) por (i,j,h)
BASE_OD    = "/content/viajes_manhattan_macrozonas_filtrados_k4.csv"  # agregados macro-macro n_viajes
REBAL_PATH = OUT/"rebalance_set.csv"                      # arcos de reequilibrio (sin h) -> replico a 96 buckets

PU, DO, BK = "macrozona_origen", "macrozona_destino", "bucket"
H = 96                          # buckets de 15 minutos (0..95)
BUCKET_MIN = 15.0               # minutos por bucket
CEIL = lambda x: int(math.ceil(float(x)))

# -------- Parámetros del modelo (ajustables)
FLEET          = 300            # tamaño de la flota total (ajusta)
SCALE_DEM      = 0.02           # % del histórico (rápido para tests)
COST_X_FACTOR  = 1.0            # costo por minuto para viajes servidos
COST_R_FACTOR  = 1.0            # costo por minuto para reequilibrio
COST_HOLD      = 0.01           # costo de mantener 1 vehículo 1 bucket "ocioso"
BIGM_UNMET     = 1e4            # penalización por viaje no atendido
USE_P90_IN_OBJ = False          # si True usa p90 en objetivo, si False usa p50

# -------- Cargar insumos
A = pd.read_csv(A_PATH)
tm = pd.read_csv(TIME_PATH)
base = pd.read_csv(BASE_OD)

# sanity: asegurar bucket en A y tm
if BK not in A.columns:
    raise ValueError("El set de arcos A por buckets debe incluir 'bucket'.")
if BK not in tm.columns:
    raise ValueError("El archivo de tiempos por bucket debe incluir 'bucket'.")

# usar p50 como costo base (o p90 si prefieres)
tm_use = tm[[PU, DO, BK, "p50", "p90"]].copy()
tm_use["p50"] = tm_use["p50"].fillna(tm_use["p50"].median())
tm_use["p90"] = tm_use["p90"].fillna(tm_use["p90"].median())

# costo por arco permitido (servicio)
A_cost = A.merge(tm_use, on=[PU,DO,BK], how="left")
if A_cost.isna().any().any():
    # fallback si faltara algo
    A_cost["p50"] = A_cost["p50"].fillna(tm_use["p50"].median())
    A_cost["p90"] = A_cost["p90"].fillna(tm_use["p90"].median())

# -------- Reequilibrio: replicar a todos los buckets
try:
    R0 = pd.read_csv(REBAL_PATH)  # columnas: PU, DO, (bucket opcional)
    if BK not in R0.columns:
        # replicar a 96 buckets
        R = R0.assign(dummy=1).merge(pd.DataFrame({BK:range(H), "dummy":[1]*H}), on="dummy", how="left").drop(columns="dummy")
    else:
        R = R0.copy()
    # quitar i==j
    R = R[R[PU] != R[DO]].copy()
except Exception as e:
    # fallback conservador: permitir reequilibrio solo entre pares que ya existen en servicio
    R = A[[PU,DO,BK]].drop_duplicates()
    R = R[R[PU] != R[DO]].copy()

# asignar costos de reequilibrio (mismos tiempos que servicio si existen; si no, usar mediana)
R_cost = R.merge(tm_use, on=[PU,DO,BK], how="left")
R_cost["p50"] = R_cost["p50"].fillna(A_cost["p50"].median())
R_cost["p90"] = R_cost["p90"].fillna(A_cost["p90"].median())

# -------- Demanda por (i,h): repartir el histórico
if "n_viajes" not in base.columns:
    raise ValueError("El archivo base debe tener columna 'n_viajes' (agregado).")
base_out = base.groupby(PU)["n_viajes"].sum().rename("W_total").reset_index()
ALL_BUCKETS = sorted(A[BK].unique())
nb = len(ALL_BUCKETS)

D = (
    base_out
    .assign(dummy=1)
    .merge(pd.DataFrame({BK:ALL_BUCKETS, "dummy":[1]*nb}), on="dummy", how="left")
    .drop(columns="dummy")
)
D["demand"] = (D["W_total"] * SCALE_DEM / nb).round().astype(int)

# asegurar al menos 1 si hay arcos desde (i,h)
valid_ih = A[[PU,BK]].drop_duplicates()
D = D.merge(valid_ih.assign(hasA=1), on=[PU,BK], how="left").fillna({"hasA":0})
D.loc[(D["demand"]==0) & (D["hasA"]==1), "demand"] = 1
D = D.drop(columns="hasA")

# —— Si quieres un patrón horario más real, aquí puedes ponderar por la proporción de salidas por bucket a partir de tus datos originales.

# -------- Precalcular “arrival bucket” para cada arco (según p50)
def add_arrival(df):
    df = df.copy()
    tb = np.ceil(df["p50"] / BUCKET_MIN).astype(int)
    df["arrive_h"] = df[BK] + tb
    df["arrive_h"] = df["arrive_h"].clip(upper=H-1)
    return df

A_timed = add_arrival(A_cost)   # servicio
R_timed = add_arrival(R_cost)   # rebalanceo

# -------- Índices y diccionarios para el modelo
# Conjunto de arcos de servicio y rebalanceo
Kx = [tuple(r) for r in A_timed[[PU,DO,BK]].itertuples(index=False)]
Kr = [tuple(r) for r in R_timed[[PU,DO,BK]].itertuples(index=False)]

# Costos
if USE_P90_IN_OBJ:
    c_x = {(i,j,h): float(t) for (i,j,h), t in zip(Kx, A_timed["p90"].values)}
    c_r = {(i,j,h): float(t) for (i,j,h), t in zip(Kr, R_timed["p90"].values)}
else:
    c_x = {(i,j,h): float(t) for (i,j,h), t in zip(Kx, A_timed["p50"].values)}
    c_r = {(i,j,h): float(t) for (i,j,h), t in zip(Kr, R_timed["p50"].values)}

# Arrival bucket mapping
arr_x = {(i,j,h): int(ah) for (i,j,h), ah in zip(Kx, A_timed["arrive_h"].values)}
arr_r = {(i,j,h): int(ah) for (i,j,h), ah in zip(Kr, R_timed["arrive_h"].values)}

# Demanda por (i,h)
IHB = [tuple(r) for r in D[[PU,BK]].drop_duplicates().itertuples(index=False)]
dih = {(i,h): int(v) for (i,h), v in zip(IHB, D["demand"].values)}

# Nodos y buckets
NODES = sorted(set(A[PU]).union(set(A[DO])))
BUCKETS = sorted(A[BK].unique())

# Para rapidez: listas de salidas por (i,h)
from collections import defaultdict
out_serv = defaultdict(list)
out_reb  = defaultdict(list)
in_serv  = defaultdict(list)
in_reb   = defaultdict(list)

for (i,j,h) in Kx:
    out_serv[(i,h)].append((i,j,h))
    in_serv[(j,arr_x[(i,j,h)])].append((i,j,h))

for (i,j,h) in Kr:
    out_reb[(i,h)].append((i,j,h))
    in_reb[(j,arr_r[(i,j,h)])].append((i,j,h))

# -------- Modelo
m = gp.Model("RideHailing_MacroBuckets_FullTest")

# Variables
x = m.addVars(Kx, vtype=GRB.INTEGER, lb=0, name="x")   # viajes servidos
r = m.addVars(Kr, vtype=GRB.INTEGER, lb=0, name="r")   # reequilibrio
s = m.addVars(NODES, BUCKETS, vtype=GRB.INTEGER, lb=0, name="s")  # stock de vehículos al inicio de bucket
u = m.addVars(NODES, BUCKETS, vtype=GRB.INTEGER, lb=0, name="u")  # demanda no atendida

# Inventario inicial (lo distribuimos proporcional a demanda por i en h=0)
# Puedes reemplazar por un vector explícito si lo tienes.
h0 = min(BUCKETS)
dem_by_i0 = pd.Series({i: sum(dih.get((i,hh),0) for hh in BUCKETS) for i in NODES})
dem_tot = dem_by_i0.sum()
if dem_tot <= 0:
    init_share = {i: 1.0/len(NODES) for i in NODES}
else:
    init_share = {i: float(dem_by_i0[i])/dem_tot for i in NODES}
init_alloc = {i: int(round(FLEET*init_share[i])) for i in NODES}
# ajuste por redondeo
diff = FLEET - sum(init_alloc.values())
for i in list(NODES)[:abs(diff)]:
    init_alloc[i] += int(np.sign(diff))

# Restricción: suma de stock inicial = FLEET
m.addConstr(gp.quicksum(s[i,h0] for i in NODES) == FLEET, name="fleet_sum_h0")

# Balance de inventario por (i,h): s(i,h+1) = s(i,h) - salidas + arribos
for h in BUCKETS:
    # capacidad de despacho (no puedes despachar más que tu stock)
    for i in NODES:
        m.addConstr(
            (gp.quicksum(x[i,j,h] for (_,j,_) in out_serv.get((i,h),[])) +
             gp.quicksum(r[i,j,h] for (_,j,_) in out_reb.get((i,h),[]))
            ) <= s[i,h],
            name=f"dispatch_cap_{i}_{h}"
        )

    # inventario al siguiente bucket (si existe)
    if h < max(BUCKETS):
        hp = h+1
        for i in NODES:
            out_x = gp.quicksum(x[i,j,h] for (_,j,_) in out_serv.get((i,h),[]))
            out_r = gp.quicksum(r[i,j,h] for (_,j,_) in out_reb.get((i,h),[]))
            in_x  = gp.quicksum(x[ii,jj,hh] for (ii,jj,hh) in in_serv.get((i,hp),[]))
            in_r  = gp.quicksum(r[ii,jj,hh] for (ii,jj,hh) in in_reb.get((i,hp),[]))
            m.addConstr(
                s[i,hp] == s[i,h] - out_x - out_r + in_x + in_r,
                name=f"stock_flow_{i}_{h}"
            )

# Demanda: sum_j x[i,j,h] + u[i,h] = D[i,h]  (si no hay demanda definida, tomamos 0)
for (i,h) in [(ii,hh) for ii in NODES for hh in BUCKETS]:
    Dih = dih.get((i,h), 0)
    m.addConstr(
        gp.quicksum(x[i,j,h] for (_,j,_) in out_serv.get((i,h),[])) + u[i,h] == Dih,
        name=f"demand_{i}_{h}"
    )

# Inicialización del stock s[i,h0] (igualdad a la asignación que construimos)
for i in NODES:
    m.addConstr(s[i,h0] == init_alloc[i], name=f"init_stock_{i}")

# Objetivo: minimizar costo servicio + reequilibrio + holding + unmet
obj  = gp.quicksum(COST_X_FACTOR * c_x[i,j,h] * x[i,j,h] for (i,j,h) in Kx)
obj += gp.quicksum(COST_R_FACTOR * c_r[i,j,h] * r[i,j,h] for (i,j,h) in Kr)
obj += gp.quicksum(COST_HOLD * s[i,h] for i in NODES for h in BUCKETS)
obj += gp.quicksum(BIGM_UNMET * u[i,h] for i in NODES for h in BUCKETS)

m.setObjective(obj, GRB.MINIMIZE)

# Parámetros de Gurobi (suaves para test)
m.Params.OutputFlag = 1
m.Params.MIPFocus = 1
m.Params.TimeLimit = 120   # ajusta si quieres
# m.Params.Threads = 4

m.optimize()

# -------- Exportar solución
def to_df_x(var, name):
    rows = []
    for k,v in var.items():
        val = v.X
        if val > 1e-6:
            rows.append((*k, int(round(val))))
    if not rows:
        return pd.DataFrame(columns=[PU,DO,BK,name])
    df = pd.DataFrame(rows, columns=[PU,DO,BK,name])
    return df.sort_values([PU,BK,DO])

x_df = to_df_x(x, "x")
r_df = to_df_x(r, "r")

s_rows = []
for i in NODES:
    for h in BUCKETS:
        val = s[i,h].X
        if val > 1e-6:
            s_rows.append((i,h,int(round(val))))
s_df = pd.DataFrame(s_rows, columns=[PU,BK,"stock"]).sort_values([PU,BK])

u_rows = []
for i in NODES:
    for h in BUCKETS:
        val = u[i,h].X
        if val > 1e-6:
            u_rows.append((i,h,int(round(val))))
u_df = pd.DataFrame(u_rows, columns=[PU,BK,"unmet"]).sort_values([PU,BK])

# guardar
(x_df).to_csv(OUT/"sol_x_service.csv", index=False)
(r_df).to_csv(OUT/"sol_r_rebalance.csv", index=False)
(s_df).to_csv(OUT/"sol_s_stock.csv", index=False)
(u_df).to_csv(OUT/"sol_u_unmet.csv", index=False)
print("OK -> soluciones en /content/outputs/")