# -*- coding: utf-8 -*-
"""Modelo Macrozonas 1.0

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ocavegqieKwXCPAibg_wd3tP1MueHhXD
"""

# ============================================================
# PRUEBA Gurobi con macrozonas k=4 (Manhattan) — Modelo base
# ============================================================
# Requiere los CSV generados en tu notebook de datos:
#   - manhattan_zonas_con_macrozona_k4.csv        (LocationID, centroid_lat, centroid_lon, macrozona)
#   - viajes_manhattan_macrozonas_filtrados_k4.csv(PUlocationID, DOlocationID, n_viajes, frecuente_80, ...)
#   - vecindad_macro_k4_union.csv                 (macrozona_A, macrozona_B)
#
# Lógica principal:
#  - Servicio (y[i,j,t,a]) SOLO en pares OD del top-80% (A80)
#  - Rebalanceo (z[i,j,t,a]) SOLO entre zonas cuyas macrozonas son vecinas (unión flujo+geografía)
#  - Posición por auto y por slot (pos[i,t,a]); balance temporal con desfase tau
#  - Demanda no atendida s[i,j,t]
#  - Objetivo: maximizar servicio - costo rebalanceo - penalización por no atender
#
# Puedes empezar así y luego enchufar tiempos/demandas reales por slot.
# ============================================================

import math
import numpy as np
import pandas as pd
from gurobipy import Model, GRB, quicksum, tuplelist

# ---------------------------
# 0) ARCHIVOS DE ENTRADA
# ---------------------------
ZONAS_CSV = "manhattan_zonas_con_macrozona_k4.csv"
PAIRS_CSV = "viajes_manhattan_macrozonas_filtrados_k4.csv"
VECIN_CSV = "vecindad_macro_k4_union.csv"

df_z   = pd.read_csv(ZONAS_CSV)
df_od  = pd.read_csv(PAIRS_CSV)
df_vec = pd.read_csv(VECIN_CSV)

# Normalizar tipos
df_z["LocationID"]     = df_z["LocationID"].astype(int)
df_od["PUlocationID"]  = df_od["PUlocationID"].astype(int)
df_od["DOlocationID"]  = df_od["DOlocationID"].astype(int)

# ---------------------------
# 1) CONJUNTOS Y MAPEOS
# ---------------------------
Z        = sorted(df_z["LocationID"].unique().tolist())            # zonas
MSET     = sorted(df_z["macrozona"].unique().tolist())             # macrozonas
macro_of = dict(df_z[["LocationID","macrozona"]].values)           # zone -> macro

# Servicio permitido: arcos OD top-80%
A80 = sorted({(int(i),int(j)) for i,j,flag in df_od[["PUlocationID","DOlocationID","frecuente_80"]].itertuples(index=False) if flag})
A80 = tuplelist(A80)

# Vecindad macro (no dirigida) + intra
Nmac = {(int(a),int(b)) for a,b in df_vec[["macrozona_A","macrozona_B"]].itertuples(index=False)}
Nmac |= {(b,a) for (a,b) in list(Nmac)}
Nmac |= {(m,m) for m in MSET}

# Rebalanceo permitido entre zonas cuyas macrozonas sean vecinas (i≠j)
R = tuplelist([(i,j) for i in Z for j in Z if i!=j and (macro_of[i], macro_of[j]) in Nmac])

# ---------------------------
# 2) HORIZONTE Y FLOTA (EDITABLE)
# ---------------------------
DELTA_MIN = 15
H         = 16              # <-- EDITA si quieres más slots (p.ej., 32 = 8h a 15')
T         = range(H)

FLEET     = 150             # <-- EDITA tamaño de flota para la prueba
A         = range(FLEET)    # índice de autos

# ---------------------------
# 3) PARÁMETROS DE DEMANDA Y TIEMPOS (PLACEHOLDER COHERENTE)
#    (puedes reemplazar por tu d_ijt y tau_ij reales)
# ---------------------------
# Frecuencias históricas por arco (para construir una demanda sintética por slot)
n_by_arc = {(int(i),int(j)): int(n) for i,j,n in df_od[["PUlocationID","DOlocationID","n_viajes"]].itertuples(index=False)}

# Perfil horario suave (pico al medio); suma = 1
hour_prof = np.array([1 + 2*np.exp(-((t - H/2)/(H/6))**2) for t in T], dtype=float)
hour_prof = hour_prof / hour_prof.sum()

# Escalamos demanda total ≈ 1.2*FLEET por horizonte (ajusta si quieres más/menos tensión)
total_hist = sum(n_by_arc.get((i,j),0) for (i,j) in set(A80))
mult = (1.2 * FLEET * len(T)) / total_hist if total_hist>0 else 0.0

# d[i,j,t] solo si (i,j)∈A80
d = {}
for (i,j) in set(A80):
    tot_ij = n_by_arc.get((i,j),0) * mult
    for t in T:
        val = float(np.floor(tot_ij * hour_prof[t] + 0.5))
        if val > 0:
            d[(i,j,t)] = val

# Tiempos de viaje (slots): intra=1, macro-vecinas=2 (placeholder; reemplaza por τ real si lo tienes)
tau = {}
for (i,j) in set(A80)|set(R):
    mi, mj = macro_of[i], macro_of[j]
    tau[(i,j)] = 1 if mi==mj else 2

# Costos/bonos simples (ajusta si tienes parámetros reales)
Dij = {(i,j): (1.0 if macro_of[i]==macro_of[j] else 2.5) for (i,j) in set(A80)|set(R)}  # proxy distancia
Pviaje = {(i,j,t): 10.0 + 2.0*Dij[(i,j)] for (i,j,t) in d.keys()}    # ingreso por servicio
Creub  = {(i,j,t):  0.5 * Dij[(i,j)]     for (i,j) in R for t in T}   # costo rebalanceo

# ---------------------------
# 4) INVENTARIO INICIAL POR ZONA Y POSICIÓN INICIAL DE AUTOS
# ---------------------------
# Reparte la flota según masa de salidas A80
out_mass = {z: 0.0 for z in Z}
for (i,j) in A80:
    out_mass[i] += n_by_arc.get((i,j),0)

init_vec = {z: (FLEET/len(Z) if sum(out_mass.values())==0 else FLEET*(out_mass[z]/sum(out_mass.values()))) for z in Z}
init_vec = {z: int(round(v)) for z,v in init_vec.items()}
res = FLEET - sum(init_vec.values())
if res != 0: init_vec[Z[0]] += res

# Mapa PosI[i,a] (auto a ubicado en zona i al inicio)
PosI = {(i,a): 0 for i in Z for a in A}
cur = 0
for i in Z:
    for _ in range(init_vec[i]):
        if cur < FLEET:
            PosI[(i,cur)] = 1
            cur += 1

# ---------------------------
# 5) MODELO GUROBI
# ---------------------------
m = Model("prueba_macro_k4")

# Variables:
# y[i,j,t,a]: servicio (solo A80)
y = m.addVars(A80, T, A, vtype=GRB.BINARY, name="y")

# z[i,j,t,a]: rebalanceo (solo R)
z = m.addVars(R,   T, A, vtype=GRB.BINARY, name="z")

# pos[i,t,a]: 1 si el auto a está en i al inicio de t
pos = m.addVars(Z, T, A, vtype=GRB.BINARY, name="pos")

# s[i,j,t]: demanda no atendida
D_keys = list(d.keys())  # solo definimos s donde existe demanda
s = m.addVars(D_keys, vtype=GRB.CONTINUOUS, lb=0.0, name="s")

m.update()

# ---------------------------
# 6) RESTRICCIONES
# ---------------------------

# 6.1 Posición inicial
for i in Z:
    for a in A:
        m.addConstr(pos[i,0,a] == PosI[(i,a)], name=f"init_pos[{i},{a}]")

# 6.2 A LO MÁS UNA ACCIÓN por auto y slot (servir o reubicar)
for t in T:
    for a in A:
        m.addConstr(
            quicksum(y[i,j,t,a] for (i,j) in A80) +
            quicksum(z[i,j,t,a] for (i,j) in R)
            <= 1,
            name=f"oneslot[{t},{a}]"
        )

# 6.3 Capacidad local: no puedes salir de i si no estás en i
for i in Z:
    for t in T:
        for a in A:
            m.addConstr(
                quicksum(y[i,j,t,a] for (ii,j) in A80.select(i,'*')) +
                quicksum(z[i,j,t,a] for (ii,j) in R.select(i,'*'))
                <= pos[i,t,a],
                name=f"cap_out[{i},{t},{a}]"
            )

# 6.4 Balance de posición (SIN variable de llegadas): pos(i,t+1) = pos(i,t) - salidas + llegadas_desfasadas
for i in Z:
    for t in T:
        for a in A:
            # salidas desde i en t
            out_t = quicksum(y[i,j,t,a] for (ii,j) in A80.select(i,'*')) \
                  + quicksum(z[i,j,t,a] for (ii,j) in R.select(i,'*'))
            # llegadas a i en t (viajes que salieron en tp con tp+tau= t)
            in_t = quicksum(
                        y[h,i,tp,a]
                        for (h,ii) in A80.select('*', i)
                        for tp in T
                        if (h,i) in tau and tp + tau[(h,i)] == t
                   ) + quicksum(
                        z[h,i,tp,a]
                        for (h,ii) in R.select('*', i)
                        for tp in T
                        if (h,i) in tau and tp + tau[(h,i)] == t
                   )
            if t < H-1:
                m.addConstr(pos[i,t+1,a] == pos[i,t,a] - out_t + in_t, name=f"bal_pos[{i},{t},{a}]")
            else:
                # último slot: factibilidad (no sobre-emitir salidas)
                m.addConstr(pos[i,t,a] >= out_t, name=f"last_feas[{i},{t},{a}]")

# 6.5 Demanda: servicio + no atendida = d_ijt (solo donde definimos demanda)
for (i,j,t), dem in d.items():
    m.addConstr(quicksum(y[i,j,t,a] for a in A) + s[i,j,t] == dem, name=f"dem[{i},{j},{t}]")

# ---------------------------
# 7) OBJETIVO
# ---------------------------
# Pesos (EDITA si quieres):
BONO_SERVICIO = 1.0   # bono por servir
COSTO_REBAL   = 0.2   # costo por rebalanceo vacío
PENAL_NOAT    = 5.0   # penal por no atender

obj  = + BONO_SERVICIO * quicksum(Pviaje[(i,j,t)] * quicksum(y[i,j,t,a] for a in A) for (i,j,t) in d.keys())
obj  += - COSTO_REBAL   * quicksum(Creub[(i,j,t)]   * quicksum(z[i,j,t,a] for a in A) for (i,j) in R for t in T)
obj  += - PENAL_NOAT    * quicksum(s[i,j,t] for (i,j,t) in d.keys())

m.setObjective(obj, GRB.MAXIMIZE)

# ---------------------------
# 8) PARÁMETROS Y RESOLVER
# ---------------------------
m.Params.TimeLimit  = 300
m.Params.MIPFocus   = 1
m.Params.Presolve   = 2
m.Params.Heuristics = 0.2
m.Params.Threads    = 0  # todos los cores

m.optimize()

# ---------------------------
# 9) REPORTE RÁPIDO
# ---------------------------
if m.SolCount > 0:
    served = sum(y[i,j,t,a].X for (i,j) in A80 for t in T for a in A)
    moved  = sum(z[i,j,t,a].X for (i,j) in R   for t in T for a in A)
    unserv = sum(s[i,j,t].X   for (i,j,t) in d.keys())
    print(f"[SOL] servidos={served:.0f}  rebalanceos={moved:.0f}  no_atendida={unserv:.0f}")

    # Algunas métricas útiles (primeras 10 zonas)
    Z10 = Z[:10]
    for i in Z10:
        out_i = sum(y[i,j,t,a].X for (ii,j) in A80.select(i,'*') for t in T for a in A) \
              + sum(z[i,j,t,a].X for (ii,j) in R.select(i,'*')   for t in T for a in A)
        inv0  = sum(PosI[(i,a)] for a in A)
        invT  = sum(pos[i,H-1,a].X for a in A)
        print(f"  zona {i}: salidas={out_i:.0f}  inv_ini={inv0}  inv_fin={invT:.0f}")
else:
    print("No hubo solución factible.")